---
- name: Enable RDP service
  tags: rdp
  become: yes
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: "fDenyTSConnections"
    type: dword
    data: 0
    state: present
- name: Enable RDP firewall rules
  tags: rdp
  become: yes
  community.windows.win_firewall_rule:
    group: "@FirewallAPI.dll,-28752"
    enabled: yes
